name: GetGift
on: workflow_dispatch
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Ollama
        run: |
          # [여기가 핵심!] 뒤에 /download/ollama-linux-amd64 가 꼭 있어야 합니다.
          curl -L https://ollama.com -o ollama_bin
          
          git config --global user.name "me"
          git config --global user.email "me@example.com"
          git add ollama_bin
          git commit -m "Now I got the REAL gift!"
          git push
